name: Build R base Image

on:
  schedule:
    - cron:  '0 0 */7 * *'
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    
    - name: Installing buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    
    
    - name: Docker hub login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    
    - name: Web-scraping ubuntu package site searching for update
      uses: docker://dr2p/r-base:update
      with:
        options: -v ${pwd}/..:/usr/Rscripts
        args: -e "source('update.R')"
    
    
    - name: Setting downloader for Github artifacts
      uses: pCYSl5EDgo/cat@master
      id: artefato
      with:
        path: ARTIFACT_ID.txt
        trim: true 

    - name: Downloading the previously artifact
      run: |
        echo $ARTIFACT_ID
        echo $DOMAIN
        echo $ENDPOINT
        echo $DOMAIN$ARTIFACT_ID$ENDPOINT
        curl -v -L -u repouser:${{ secrets.GITHUB_TOKEN }} -o current_version.zip $DOMAIN$ARTIFACT_ID$ENDPOINT
      env:
        ARTIFACT_ID: ${{ steps.artefato.outputs.text }}
        DOMAIN: 'https://api.github.com/repos/dr2pedro/baseR-multiarch-Docker-image/actions/artifacts/'
        ENDPOINT: '/zip' 

    - name: Setting an unziper
      uses: montudor/action-zip@v0.1.0
      with:
        args: unzip -qq current_version.zip
    
    - name: Setting an uploader
      uses: pCYSl5EDgo/cat@master
      id: current_R_version
      with:
        path: R-version.txt
        trim: true 
    
    - name: Downloading web-scraping results
      uses: pCYSl5EDgo/cat@master
      id: available_R_version
      with:
        path: R-version-available.txt
        trim: true    
    
    - name: Comparing versions and building(+push) in casse they are diferent
      run: |
       if [ "x$s1" == "x$s2" ] ; 
       then echo "They are the same version" ; 
       else docker buildx build --push --tag dr2p/r-base:latest --platform linux/amd64,linux/arm64 . && curl -X POST -H 'Content-type: application/json' --data ${{ toJson(secrets.SLACK_MESSAGE) }} ${{ secrets.SLACK_WEBHOOK }}; fi
      env: 
       s1: ${{ steps.current_R_version.outputs.text }}
       s2: ${{ steps.available_R_version.outputs.text }}
    
    - name: Testing and making the next artifact
      uses: docker://dr2p/r-base
      with:
        args: -e "write.table(as.character(getRversion()),'R-version.txt',sep='',row.names=FALSE,col.names=FALSE)"
    
    - name: Uploading the artifact
      uses: actions/upload-artifact@v2
      with:
        name: current_version
        path: R-version.txt
