# This is a basic workflow to help you get started with Actions

name: Build Docker Image

on:
  push:
    branches: [ tidyverse ]
name: build image with buildx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: instalando buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: login no docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: build da imagem
      run: |
        docker buildx build --push \
          --tag dr2p/r-base:tidyverse \
          --platform linux/amd64,linux/arm64 .
