name: Build R base Image

on:
  push:
    branches: [ update ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: instalando buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: login no docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: build all images
      run: |
        docker buildx build --push --tag dr2p/r-base:update --build-arg version=4.0.1 --platform linux/amd64,linux/arm64 .
    - name: test it!
      uses: docker://dr2p/r-base
      with:
        args: -e "write.table(as.character(getRversion()),'R-version.txt',sep='',row.names=FALSE,col.names=FALSE)"
    - name: Upload txt result for r-base
      uses: actions/upload-artifact@v2
      with:
       name: current_version
       path: R-version.txt
