name: Build R base Image

on:
  push:
    branches: [ tiny ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: instalando buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: login no docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: build da imagem amd64
      run: |
        docker buildx build --push --tag dr2p/r-base:amd64 --platform linux/amd64 .
    - name: build da imagem arm64
      run: |
        docker buildx build --push --tag dr2p/r-base:arm64 --platform linux/arm64 .
      
