name: build image with buildx

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: build the image
      run: |
        docker buildx build \
          --tag dr2p/r-base:latest \
          --platform linux/amd64,linux/arm64 .
