name: Build R base Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    
    - name: instalando buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    
    
    - name: login no docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    
    - name: check update
      uses: docker://dr2p/r-base:update
      with:
        options: -v ${pwd}/..:/usr/Rscripts
        args: -e "source('update.R')"
    
    
    - uses: pCYSl5EDgo/cat@master
      id: artefato
      with:
        path: ARTIFACT_ID.txt
        trim: true 

    
    - run: |
        echo $ARTIFACT_ID
        echo $DOMAIN
        echo $ENDPOINT
        echo $DOMAIN$ARTIFACT_ID$ENDPOINT
        curl -v -L -u repouser:${{ secrets.GITHUB_TOKEN }} -o current_version.zip $DOMAIN$ARTIFACT_ID$ENDPOINT
      env:
        ARTIFACT_ID: ${{ steps.artefato.outputs.text }}
        DOMAIN: 'https://api.github.com/repos/dr2pedro/baseR-multiarch-Docker-image/actions/artifacts/'
        ENDPOINT: '/zip' 

    - uses: montudor/action-zip@v0.1.0
      with:
        args: unzip -qq current_version.zip
    
    - uses: pCYSl5EDgo/cat@master
      id: current_R_version
      with:
        path: R-version.txt
        trim: true 
    
    - uses: pCYSl5EDgo/cat@master
      id: available_R_version
      with:
        path: R-version-available.txt
        trim: true    
    
    - run: |
       if [ "x$s1" == "x$s2" ] ; then echo "They are the same" else echo "They are not the same" fi
      env: 
       s1: ${{ steps.current_R_version.outputs.text }}
       s2: ${{ steps.available_R_version.outputs.text }}
